package se.mobileinteraction.image;

public class ColorNames {

    public class ColorName {

        private final String name;
        private final int rgbColor;
        private final int red;
        private final int green;
        private final int blue;

        public ColorName(String name, int rgbColor) {
            this.name = name;
            this.rgbColor = rgbColor;
            this.red = (rgbColor >> 16) & 0xff;
            this.green = (rgbColor >> 8) & 0xff;
            this.blue = (rgbColor) & 0xff;
        }
    }

    public ColorName[] colorNames = new ColorName[]{
            new ColorName("Absolute Zero", 0x0048BA),
            new ColorName("Acajou", 0x4C2F27),
            new ColorName("Acid green", 0xB0BF1A),
            new ColorName("Aero", 0x7CB9E8),
            new ColorName("Aero blue", 0xC9FFE5),
            new ColorName("African violet", 0xB284BE),
            new ColorName("Air Force blue (RAF)", 0x5D8AA8),
            new ColorName("Air Force blue (USAF)", 0x00308F),
            new ColorName("Air superiority blue", 0x72A0C1),
            new ColorName("Alabama crimson", 0xAF002A),
            new ColorName("Alabaster", 0xF2F0E6),
            new ColorName("Alice blue", 0xF0F8FF),
            new ColorName("Alizarin crimson", 0xE32636),
            new ColorName("Alloy orange", 0xC46210),
            new ColorName("Almond", 0xEFDECD),
            new ColorName("Aluminum", 0xD6D6D6),
            new ColorName("Amaranth", 0xE52B50),
            new ColorName("Amaranth deep purple", 0x9F2B68),
            new ColorName("Amaranth pink", 0xF19CBB),
            new ColorName("Amaranth purple", 0xAB274F),
            new ColorName("Amaranth red", 0xD3212D),
            new ColorName("Amazon", 0x3B7A57),
            new ColorName("Amber", 0xFFBF00),
            new ColorName("Amber (SAE/ECE)", 0xFF7E00),
            new ColorName("American blue", 0x3B3B6D),
            new ColorName("American bronze", 0x391802),
            new ColorName("American brown", 0x804040),
            new ColorName("American gold", 0xD3AF37),
            new ColorName("American green", 0x34B334),
            new ColorName("American orange", 0xFF8B00),
            new ColorName("American pink", 0xFF9899),
            new ColorName("American purple", 0x431C53),
            new ColorName("American red", 0xB32134),
            new ColorName("American rose", 0xFF033E),
            new ColorName("American silver", 0xCFCFCF),
            new ColorName("American violet", 0x551B8C),
            new ColorName("American yellow", 0xF2B400),
            new ColorName("Amethyst", 0x9966CC),
            new ColorName("Android green (2008-2014)", 0xA4C639),
            new ColorName("Android green", 0x79C257),
            new ColorName("Anti-flash white", 0xF2F3F4),
            new ColorName("Antique brass", 0xCD9575),
            new ColorName("Antique bronze", 0x665D1E),
            new ColorName("Antique fuchsia", 0x915C83),
            new ColorName("Antique ruby", 0x841B2D),
            new ColorName("Antique white", 0xFAEBD7),
            new ColorName("Ao (English)", 0x008000),
            new ColorName("Apple", 0x66B447),
            new ColorName("Apple green", 0x8DB600),
            new ColorName("Apricot", 0xFBCEB1),
            new ColorName("Aqua", 0x00FFFF),
            new ColorName("Aquamarine", 0x7FFFD4),
            new ColorName("Arctic lime", 0xD0FF14),
            new ColorName("Argent", 0xC0C0C0),
            new ColorName("Army green", 0x4B5320),
            new ColorName("Arsenic", 0x3B444B),
            new ColorName("Artichoke", 0x8F9779),
            new ColorName("Arylide yellow", 0xE9D66B),
            new ColorName("Asda Green", 0x7DC242),
            new ColorName("Asda Green (2002)", 0x32AD61),
            new ColorName("Asda Green (1999)", 0x66C992),
            new ColorName("Asda Green (1994)", 0x80C197),
            new ColorName("Asda Green (1985)", 0x00DEA4),
            new ColorName("Asda Orange", 0xC86500),
            new ColorName("Asda Orange (1968)", 0xCA7309),
            new ColorName("Ash gray", 0xB2BEB5),
            new ColorName("Asparagus", 0x87A96B),
            new ColorName("Ateneo blue", 0x003A6C),
            new ColorName("Atomic tangerine", 0xFF9966),
            new ColorName("Auburn", 0xA52A2A),
            new ColorName("Aureolin", 0xFDEE00),
            new ColorName("AuroMetalSaurus", 0x6E7F80),
            new ColorName("Avocado", 0x568203),
            new ColorName("Awesome", 0xFF2052),
            new ColorName("Axolotl", 0x63775B),
            new ColorName("Azure", 0x007FFF),
            new ColorName("Azure mist", 0xF0FFFF),
            new ColorName("Azureish white", 0xDBE9F4),
            new ColorName("Baby blue", 0x89CFF0),
            new ColorName("Baby blue eyes", 0xA1CAF1),
            new ColorName("Baby pink", 0xF4C2C2),
            new ColorName("Baby powder", 0xFEFEFA),
            new ColorName("Baker-Miller pink", 0xFF91AF),
            new ColorName("Ball blue", 0x21ABCD),
            new ColorName("Banana Mania", 0xFAE7B5),
            new ColorName("Banana yellow", 0xFFE135),
            new ColorName("Bangladesh green", 0x006A4E),
            new ColorName("Barbie Pink (1959-1975)", 0xE85395),
            new ColorName("Barbie Pink (1975-1990)", 0xD3419D),
            new ColorName("Barbie Pink (1990-1999)", 0xF364A2),
            new ColorName("Barbie Pink (1999-2004)", 0xF7238A),
            new ColorName("Barbie Pink (2004-2005)", 0xFF3988),
            new ColorName("Barbie Pink (2005-2009)", 0xFC419A),
            new ColorName("Barbie Pink", 0xE94196),
            new ColorName("Barbie Pink (Pantone)", 0xE0218A),
            new ColorName("Barn red", 0x7C0A02),
            new ColorName("Battery charged blue", 0x1DACD6),
            new ColorName("Battleship grey", 0x848482),
            new ColorName("Batorange", 0xC3540A),
            new ColorName("Bayside", 0x5FC9BF),
            new ColorName("Bazaar", 0x98777B),
            new ColorName("Beau blue", 0xBCD4E6),
            new ColorName("Beaver", 0x9F8170),
            new ColorName("Beer", 0xF28E1C),
            new ColorName("Begonia", 0xFA6E79),
            new ColorName("Beige", 0xF5F5DC),
            new ColorName("B'dazzled blue", 0x2E5894),
            new ColorName("Big dip o’ruby", 0x9C2542),
            new ColorName("Big Foot Feet", 0xE88E5A),
            new ColorName("Bisque", 0xFFE4C4),
            new ColorName("Bistre", 0x3D2B1F),
            new ColorName("Bistre brown", 0x967117),
            new ColorName("Bitter lemon", 0xCAE00D),
            new ColorName("Bitter lime", 0xBFFF00),
            new ColorName("Bittersweet", 0xFE6F5E),
            new ColorName("Bittersweet shimmer", 0xBF4F51),
            new ColorName("Black", 0x000000),
            new ColorName("Black bean", 0x3D0C02),
            new ColorName("Black chocolate", 0x1B1811),
            new ColorName("Black coffee", 0x3B2F2F),
            new ColorName("Black coral", 0x54626F),
            new ColorName("Black leather jacket", 0x253529),
            new ColorName("Black olive", 0x3B3C36),
            new ColorName("Blackberry", 0x8F5973),
            new ColorName("Black raspberry", 0x16110D),
            new ColorName("Black Shadows", 0xBFAFB2),
            new ColorName("Blanched almond", 0xFFEBCD),
            new ColorName("Blast-off bronze", 0xA57164),
            new ColorName("Bleu de France", 0x318CE7),
            new ColorName("Blizzard blue", 0xACE5EE),
            new ColorName("Blond", 0xFAF0BE),
            new ColorName("Blood", 0x8A0303),
            new ColorName("Blood orange", 0xD1001C),
            new ColorName("Blood red", 0x660000),
            new ColorName("Blood (Animal)", 0xA41313),
            new ColorName("Blood (organ)", 0x630F0F),
            new ColorName("Blue", 0x0000FF),
            new ColorName("Blue (Crayola)", 0x1F75FE),
            new ColorName("Blue (Munsell)", 0x0093AF),
            new ColorName("Blue (NCS)", 0x0087BD),
            new ColorName("Blue (Pantone)", 0x0018A8),
            new ColorName("Blue (pigment)", 0x333399),
            new ColorName("Blue (RYB)", 0x0247FE),
            new ColorName("Blue bell", 0xA2A2D0),
            new ColorName("Blue bolt", 0x00B9FB),
            new ColorName("Blue cola", 0x0088DC),
            new ColorName("Blue-gray", 0x6699CC),
            new ColorName("Blue-green", 0x0D98BA),
            new ColorName("Blue-green (color wheel)", 0x064E40),
            new ColorName("Blue jeans", 0x5DADEC),
            new ColorName("Blue lagoon", 0xACE5EE),
            new ColorName("Blue-magenta violet", 0x553592),
            new ColorName("Blue (Nicole and Bri)", 0x0095B6),
            new ColorName("Blue raspberry", 0x0CBFE9),
            new ColorName("Blue sapphire", 0x126180),
            new ColorName("Blue-violet", 0x8A2BE2),
            new ColorName("Blue-violet (Crayola)", 0x7366BD),
            new ColorName("Blue-violet (color wheel)", 0x4D1A7F),
            new ColorName("Blue yonder", 0x5072A7),
            new ColorName("Blueberry", 0x4F86F7),
            new ColorName("Bluebonnet", 0x1C1CF0),
            new ColorName("Blush", 0xDE5D83),
            new ColorName("Bole", 0x79443B),
            new ColorName("Bone", 0xE3DAC9),
            new ColorName("Bored accent green", 0xDDE26A),
            new ColorName("Boston University red", 0xCC0000),
            new ColorName("Bottle green", 0x006A4E),
            new ColorName("Boysenberry", 0x873260),
            new ColorName("Boy red", 0x0E9CA5),
            new ColorName("Brandeis blue", 0x0070FF),
            new ColorName("Brandy", 0x87413F),
            new ColorName("Brass", 0xB5A642),
            new ColorName("Brave orange", 0xFF631C),
            new ColorName("Brick red", 0xCB4154),
            new ColorName("Bright cerulean", 0x1DACD6),
            new ColorName("Bright gray", 0xEBECF0),
            new ColorName("Bright green", 0x66FF00),
            new ColorName("Bright lavender", 0xBF94E4),
            new ColorName("Bright lilac", 0xD891EF),
            new ColorName("Bright maroon", 0xC32148),
            new ColorName("Bright navy blue", 0x1974D2),
            new ColorName("Bright pink", 0xFF007F),
            new ColorName("Bright turquoise", 0x08E8DE),
            new ColorName("Bright ube", 0xD19FE8),
            new ColorName("Bright yellow (Crayola)", 0xFFAA1D),
            new ColorName("Brilliant azure", 0x3399FF),
            new ColorName("Brilliant lavender", 0xF4BBFF),
            new ColorName("Brilliant rose", 0xFF55A3),
            new ColorName("Brink pink", 0xFB607F),
            new ColorName("British racing green", 0x004225),
            new ColorName("Bronze", 0x88540B),
            new ColorName("Bronze", 0xCD7F32),
            new ColorName("Bronze (metallic)", 0xB08D57),
            new ColorName("Bronze yellow", 0x737000),
            new ColorName("Brown", 0x993300),
            new ColorName("Brown (Crayola)", 0xAF593E),
            new ColorName("Brown (traditional)", 0x964B00),
            new ColorName("Brown (web)", 0xA52A2A),
            new ColorName("Brown-nose", 0x6B4423),
            new ColorName("Brown sugar", 0xAF6E4D),
            new ColorName("Brown Chocolate", 0x5F1933),
            new ColorName("Brown Coffee", 0x4A2C2A),
            new ColorName("Brown Yellow", 0xCC9966),
            new ColorName("Brunswick green", 0x1B4D3E),
            new ColorName("Bubble gum", 0xFFC1CC),
            new ColorName("Bubbles", 0xE7FEFF),
            new ColorName("Bud green", 0x7BB661),
            new ColorName("Buff", 0xF0DC82),
            new ColorName("Bulgarian rose", 0x480607),
            new ColorName("Burgundy", 0x800020),
            new ColorName("Burlywood", 0xDEB887),
            new ColorName("Burnished brown", 0xA17A74),
            new ColorName("Burnt orange", 0xCC5500),
            new ColorName("Burnt sienna", 0xE97451),
            new ColorName("Burnt umber", 0x8A3324),
            new ColorName("Button blue", 0x24A0ED),
            new ColorName("Byzantine", 0xBD33A4),
            new ColorName("Byzantium", 0x702963),
            new ColorName("Cadet", 0x536872),
            new ColorName("Cadet blue", 0x5F9EA0),
            new ColorName("Cadet blue (Crayola)", 0xA9B2C3),
            new ColorName("Cadet grey", 0x91A3B0),
            new ColorName("Cadmium blue", 0x0A1195),
            new ColorName("Cadmium green", 0x006B3C),
            new ColorName("Cadmium orange", 0xED872D),
            new ColorName("Cadmium purple", 0xB60C26),
            new ColorName("Cadmium red", 0xE30022),
            new ColorName("Cadmium yellow", 0xFFF600),
            new ColorName("Cadmium violet", 0x7F3E98),
            new ColorName("Café au lait", 0xA67B5B),
            new ColorName("Café noir", 0x4B3621),
            new ColorName("Cal Poly Pomona green", 0x1E4D2B),
            new ColorName("Calamansi", 0xFCFFA4),
            new ColorName("Cambridge blue", 0xA3C1AD),
            new ColorName("Camel", 0xC19A6B),
            new ColorName("Cameo pink", 0xEFBBCC),
            new ColorName("Camouflage green", 0x78866B),
            new ColorName("Canary", 0xFFFF99),
            new ColorName("Canary yellow", 0xFFEF00),
            new ColorName("Candy apple red", 0xFF0800),
            new ColorName("Candy pink", 0xE4717A),
            new ColorName("Capri", 0x00BFFF),
            new ColorName("Caput mortuum", 0x592720),
            new ColorName("Caramel", 0xFFD59A),
            new ColorName("Cardinal", 0xC41E3A),
            new ColorName("Caribbean green", 0x00CC99),
            new ColorName("Caribbean blue", 0x1AC1DD),
            new ColorName("Carmine", 0x960018),
            new ColorName("Carmine (M&P)", 0xD70040),
            new ColorName("Carmine pink", 0xEB4C42),
            new ColorName("Carmine red", 0xFF0038),
            new ColorName("Carnation pink", 0xFFA6C9),
            new ColorName("Carnelian", 0xB31B1B),
            new ColorName("Carolina blue", 0x56A0D3),
            new ColorName("Carrot orange", 0xED9121),
            new ColorName("Castleton green", 0x00563F),
            new ColorName("Catalina blue", 0x062A78),
            new ColorName("Catawba", 0x703642),
            new ColorName("Cedar Chest", 0xC95A49),
            new ColorName("Ceil", 0x92A1CF),
            new ColorName("Celadon", 0xACE1AF),
            new ColorName("Celadon blue", 0x007BA7),
            new ColorName("Celadon green", 0x2F847C),
            new ColorName("Celeste", 0xB2FFFF),
            new ColorName("Celestial blue", 0x4997D0),
            new ColorName("Celtic blue", 0x246BCE),
            new ColorName("Cerise", 0xDE3163),
            new ColorName("Cerise pink", 0xEC3B83),
            new ColorName("Cerulean", 0x007BA7),
            new ColorName("Cerulean blue", 0x2A52BE),
            new ColorName("Cetacean blue", 0x001440),
            new ColorName("Cerulean frost", 0x6D9BC3),
            new ColorName("Cerulean (Crayola)", 0x1DACD6),
            new ColorName("CG blue", 0x007AA5),
            new ColorName("CG red", 0xE03C31),
            new ColorName("Chamoisee", 0xA0785A),
            new ColorName("Champagne", 0xF7E7CE),
            new ColorName("Champagne pink", 0xF1DDCF),
            new ColorName("Charcoal", 0x36454F),
            new ColorName("Charleston green", 0x232B2B),
            new ColorName("Charm", 0xD0748B),
            new ColorName("Charm pink", 0xE68FAC),
            new ColorName("Chartreuse (traditional)", 0xDFFF00),
            new ColorName("Chartreuse (web)", 0x7FFF00),
            new ColorName("Cheese", 0xFFA600),
            new ColorName("Cherry", 0xDE3163),
            new ColorName("Cherry blossom pink", 0xFFB7C5),
            new ColorName("Chestnut", 0x954535),
            new ColorName("Chickadee", 0xFFC34D),
            new ColorName("China pink", 0xDE6FA1),
            new ColorName("China rose", 0xA8516E),
            new ColorName("Chinese black", 0x141414),
            new ColorName("Chinese blue", 0x365194),
            new ColorName("Chinese bronze", 0xCD8032),
            new ColorName("Chinese brown", 0xAB381F),
            new ColorName("Chinese green", 0xD0DB61),
            new ColorName("Chinese gold", 0xCC9900),
            new ColorName("Chinese orange", 0xF37042),
            new ColorName("Chinese pink", 0xDE70A1),
            new ColorName("Chinese purple", 0x720B98),
            new ColorName("Chinese red", 0xCD071E),
            new ColorName("Chinese red", 0xAA381E),
            new ColorName("Chinese silver", 0xCCCCCC),
            new ColorName("Chinese violet", 0x856088),
            new ColorName("Chinese white", 0xE2E5DE),
            new ColorName("Chinese yellow", 0xFFB200),
            new ColorName("Chlorophyll green", 0x4AFF00),
            new ColorName("Chocolate brown", 0x3F000F),
            new ColorName("Chocolate cosmos", 0x58111A),
            new ColorName("Chocolate Kisses", 0x3C1421),
            new ColorName("Chocolate (traditional)", 0x7B3F00),
            new ColorName("Chocolate (web)", 0xD2691E),
            new ColorName("Christmas blue", 0x2A8FBD),
            new ColorName("Christmas blue", 0x365194),
            new ColorName("Christmas brown", 0x5D2B2C),
            new ColorName("Christmas brown", 0x4C1F02),
            new ColorName("Christmas green", 0x3C8D0D),
            new ColorName("Christmas green", 0x007502),
            new ColorName("Christmas gold", 0xCAA906),
            new ColorName("Christmas orange", 0xFF6600),
            new ColorName("Christmas orange", 0xD56C2B),
            new ColorName("Christmas pink", 0xFFCCCB),
            new ColorName("Christmas pink", 0xE34285),
            new ColorName("Christmas purple", 0x663398),
            new ColorName("Christmas purple", 0x4D084B),
            new ColorName("Christmas red", 0xAA0114),
            new ColorName("Christmas red", 0xB01B2E),
            new ColorName("Christmas silver", 0xE1DFE0),
            new ColorName("Christmas yellow", 0xFFCC00),
            new ColorName("Christmas yellow", 0xFEF200),
            new ColorName("Chrome aluminum", 0xA8A9AD),
            new ColorName("Chrome yellow", 0xFFA700),
            new ColorName("Cinereous", 0x98817B),
            new ColorName("Cinnabar", 0xE34234),
            new ColorName("Cinnamon[citation needed]", 0xD2691E),
            new ColorName("Cinnamon Satin", 0xCD607E),
            new ColorName("Citrine", 0xE4D00A),
            new ColorName("Citrine Brown", 0x933709),
            new ColorName("Citron", 0x9FA91F),
            new ColorName("Claret", 0x7F1734),
            new ColorName("Classic rose", 0xFBCCE7),
            new ColorName("Cobalt blue", 0x0047AB),
            new ColorName("Cocoa brown", 0xD2691E),
            new ColorName("Coconut", 0x965A3E),
            new ColorName("Coconut White", 0xE9EDF6),
            new ColorName("Coffee", 0x6F4E37),
            new ColorName("Cola", 0x3C3024),
            new ColorName("Columbia Blue", 0xC4D8E2),
            new ColorName("Conditioner", 0xFFFFCC),
            new ColorName("Congo pink", 0xF88379),
            new ColorName("Cool black", 0x002E63),
            new ColorName("Cool grey", 0x8C92AC),
            new ColorName("Cookies and cream", 0xEEE0B1),
            new ColorName("Copper", 0xB87333),
            new ColorName("Copper (Crayola)", 0xDA8A67),
            new ColorName("Copper penny", 0xAD6F69),
            new ColorName("Copper red", 0xCB6D51),
            new ColorName("Copper rose", 0x996666),
            new ColorName("Coquelicot", 0xFF3800),
            new ColorName("Coral", 0xFF7F50),
            new ColorName("Coral pink", 0xF88379),
            new ColorName("Coral red", 0xFF4040),
            new ColorName("Coral reef", 0xFD7C6E),
            new ColorName("Coral Reef (Valspar Paint Color)", 0xF6A494),
            new ColorName("Cordovan", 0x893F45),
            new ColorName("Corn", 0xFBEC5D),
            new ColorName("Cornell red", 0xB31B1B),
            new ColorName("Cornflower blue", 0x6495ED),
            new ColorName("Cornflower", 0x93CCEA),
            new ColorName("Cornsilk", 0xFFF8DC),
            new ColorName("Cosmic cobalt", 0x2E2D88),
            new ColorName("Cosmic latte", 0xFFF8E7),
            new ColorName("Coyote brown", 0x81613C),
            new ColorName("Cotton candy", 0xFFBCD9),
            new ColorName("Cream", 0xFFFDD0),
            new ColorName("Crimson", 0xDC143C),
            new ColorName("Crimson glory", 0xBE0032),
            new ColorName("Crimson red", 0x990000),
            new ColorName("Crystal", 0xA7D8DE),
            new ColorName("Crystal blue", 0x68A0B0),
            new ColorName("Cultured", 0xF5F5F5),
            new ColorName("Cyan", 0x00FFFF),
            new ColorName("Cyan azure", 0x4E82B4),
            new ColorName("Cyan-blue azure", 0x4682BF),
            new ColorName("Cyan cobalt blue", 0x28589C),
            new ColorName("Cyan cornflower blue", 0x188BC2),
            new ColorName("Cyan (process)", 0x00B7EB),
            new ColorName("Cyber grape", 0x58427C),
            new ColorName("Cyber yellow", 0xFFD300),
            new ColorName("Cyclamen", 0xF56FA1),
            new ColorName("Daffodil", 0xFFFF31),
            new ColorName("Dandelion", 0xF0E130),
            new ColorName("Dandelion (Crayola)", 0xFDDB6D),
            new ColorName("Dark blue", 0x00008B),
            new ColorName("Dark blue-gray", 0x666699),
            new ColorName("Dark bronze", 0x804A00),
            new ColorName("Dark bronze (Coin)", 0x514100),
            new ColorName("Dark brown", 0x654321),
            new ColorName("Dark brown-tangelo", 0x88654E),
            new ColorName("Dark byzantium", 0x5D3954),
            new ColorName("Dark candy apple red", 0xA40000),
            new ColorName("Dark cerulean", 0x08457E),
            new ColorName("Dark charcoal", 0x333333),
            new ColorName("Dark chestnut", 0x986960),
            new ColorName("Dark chocolate", 0x490206),
            new ColorName("Dark chocolate (Hershey's)", 0x3C1321),
            new ColorName("Dark cornflower blue", 0x26428B),
            new ColorName("Dark coral", 0xCD5B45),
            new ColorName("Dark cyan", 0x008B8B),
            new ColorName("Dark electric blue", 0x536878),
            new ColorName("Dark gold", 0xAA6C39),
            new ColorName("Dark goldenrod", 0xB8860B),
            new ColorName("Dark gray (X11)", 0xA9A9A9),
            new ColorName("Dark green", 0x013220),
            new ColorName("Dark green (X11)", 0x006400),
            new ColorName("Dark gunmetal", 0x1F262A),
            new ColorName("Dark imperial blue", 0x00416A),
            new ColorName("Dark imperial blue", 0x00147E),
            new ColorName("Dark jungle green", 0x1A2421),
            new ColorName("Dark khaki", 0xBDB76B),
            new ColorName("Dark lava", 0x483C32),
            new ColorName("Dark lavender", 0x734F96),
            new ColorName("Dark lemon lime", 0x8BBE1B),
            new ColorName("Dark liver", 0x534B4F),
            new ColorName("Dark liver (horses)", 0x543D37),
            new ColorName("Dark magenta", 0x8B008B),
            new ColorName("Dark medium gray", 0xA9A9A9),
            new ColorName("Dark midnight blue", 0x003366),
            new ColorName("Dark moss green", 0x4A5D23),
            new ColorName("Dark Navy", 0x02075D),
            new ColorName("Dark olive green", 0x556B2F),
            new ColorName("Dark orange", 0xFF8C00),
            new ColorName("Dark orchid", 0x9932CC),
            new ColorName("Dark pastel blue", 0x779ECB),
            new ColorName("Dark pastel green", 0x03C03C),
            new ColorName("Dark pastel purple", 0x966FD6),
            new ColorName("Dark pastel red", 0xC23B22),
            new ColorName("Dark pink", 0xE75480),
            new ColorName("Dark powder blue", 0x003399),
            new ColorName("Dark puce", 0x4F3A3C),
            new ColorName("Dark purple", 0x301934),
            new ColorName("Dark raspberry", 0x872657),
            new ColorName("Dark red", 0x8B0000),
            new ColorName("Dark salmon", 0xE9967A),
            new ColorName("Dark scarlet", 0x560319),
            new ColorName("Dark sea green", 0x8FBC8F),
            new ColorName("Dark sienna", 0x3C1414),
            new ColorName("Dark silver", 0x71706E),
            new ColorName("Dark sky blue", 0x8CBED6),
            new ColorName("Dark slate blue", 0x483D8B),
            new ColorName("Dark slate gray", 0x2F4F4F),
            new ColorName("Dark spring green", 0x177245),
            new ColorName("Dark tan", 0x918151),
            new ColorName("Dark tangerine", 0xFFA812),
            new ColorName("Dark taupe", 0x483C32),
            new ColorName("Dark terra cotta", 0xCC4E5C),
            new ColorName("Dark turquoise", 0x00CED1),
            new ColorName("Dark vanilla", 0xD1BEA8),
            new ColorName("Dark violet", 0x9400D3),
            new ColorName("Dark yellow", 0x9B870C),
            new ColorName("Dartmouth green", 0x00703C),
            new ColorName("Davy's grey", 0x555555),
            new ColorName("Debian red", 0xD70A53),
            new ColorName("Deep amethyst", 0x9C8AA4),
            new ColorName("Deep aquamarine", 0x40826D),
            new ColorName("Deep carmine", 0xA9203E),
            new ColorName("Deep carmine pink", 0xEF3038),
            new ColorName("Deep carrot orange", 0xE9692C),
            new ColorName("Deep cerise", 0xDA3287),
            new ColorName("Deep champagne", 0xFAD6A5),
            new ColorName("Deep chestnut", 0xB94E48),
            new ColorName("Deep coffee", 0x704241),
            new ColorName("Deep dumpling", 0x9B351B),
            new ColorName("Deep fuchsia", 0xC154C1),
            new ColorName("Deep green", 0x056608),
            new ColorName("Deep green-cyan turquoise", 0x0E7C61),
            new ColorName("Deep jungle green", 0x004B49),
            new ColorName("Deep koamaru", 0x333366),
            new ColorName("Deep lemon", 0xF5C71A),
            new ColorName("Deep lilac", 0x9955BB),
            new ColorName("Deep magenta", 0xCC00CC),
            new ColorName("Deep maroon", 0x820000),
            new ColorName("Deep mauve", 0xD473D4),
            new ColorName("Deep moss green", 0x355E3B),
            new ColorName("Deep peach", 0xFFCBA4),
            new ColorName("Deep pink", 0xFF1493),
            new ColorName("Deep puce", 0xA95C68),
            new ColorName("Deep red", 0x850101),
            new ColorName("Deep ruby", 0x843F5B),
            new ColorName("Deep saffron", 0xFF9933),
            new ColorName("Deep sky blue", 0x00BFFF),
            new ColorName("Deep Space Sparkle", 0x4A646C),
            new ColorName("Deep spring bud", 0x556B2F),
            new ColorName("Deep taupe", 0x7E5E60),
            new ColorName("Deep Tuscan red", 0x66424D),
            new ColorName("Deep violet", 0x330066),
            new ColorName("Deer", 0xBA8759),
            new ColorName("Denim", 0x1560BD),
            new ColorName("Denim blue", 0x2243B6),
            new ColorName("Desaturated cyan", 0x669999),
            new ColorName("Desert", 0xC19A6B),
            new ColorName("Desert sand", 0xEDC9AF),
            new ColorName("Desire", 0xEA3C53),
            new ColorName("Diamond", 0xB9F2FF),
            new ColorName("Dim gray", 0x696969),
            new ColorName("Dingy Dungeon", 0xC53151),
            new ColorName("Dirt", 0x9B7653),
            new ColorName("Dirty brown", 0xB5651E),
            new ColorName("Dirty white", 0xE8E4C9),
            new ColorName("Dodger blue", 0x1E90FF),
            new ColorName("Dodie yellow", 0xFEF65B),
            new ColorName("Dogwood rose", 0xD71868),
            new ColorName("Dollar bill", 0x85BB65),
            new ColorName("Dolphin gray", 0x828E84),
            new ColorName("Douban Blue", 0x2496CD),
            new ColorName("Douban Green", 0x2E963D),
            new ColorName("Douban Light Yellow", 0xF7C58E),
            new ColorName("Drab", 0x967117),
            new ColorName("Duke blue", 0x00009C),
            new ColorName("Durian", 0xB07939),
            new ColorName("Durian White", 0xE6D0AB),
            new ColorName("Durian Yellow", 0xE1BD27),
            new ColorName("Dust storm", 0xE5CCC9),
            new ColorName("Dutch white", 0xEFDFBB),
            new ColorName("Earthtone", 0x5D3A1A),
            new ColorName("Earth yellow", 0xE1A95F),
            new ColorName("Ebony", 0x555D50),
            new ColorName("Ecru", 0xC2B280),
            new ColorName("Eerie black", 0x1B1B1B),
            new ColorName("Eggplant", 0x614051),
            new ColorName("Eggshell", 0xF0EAD6),
            new ColorName("Egyptian blue", 0x1034A6),
            new ColorName("Elderberry", 0x17182B),
            new ColorName("Electric blue", 0x7DF9FF),
            new ColorName("Electric brown", 0xB56257),
            new ColorName("Electric crimson", 0xFF003F),
            new ColorName("Electric cyan", 0x00FFFF),
            new ColorName("Electric green", 0x00FF00),
            new ColorName("Electric indigo", 0x6F00FF),
            new ColorName("Electric lavender", 0xF4BBFF),
            new ColorName("Electric lime", 0xCCFF00),
            new ColorName("Electric orange", 0xFF3503),
            new ColorName("Electric pink", 0xF62681),
            new ColorName("Electric purple", 0xBF00FF),
            new ColorName("Electric red", 0xE60000),
            new ColorName("Electric ultramarine", 0x3F00FF),
            new ColorName("Electric violet", 0x8F00FF),
            new ColorName("Electric yellow", 0xFFFF33),
            new ColorName("Emerald", 0x50C878),
            new ColorName("Emerald green", 0x046307),
            new ColorName("Eminence", 0x6C3082),
            new ColorName("English green", 0x1B4D3E),
            new ColorName("English lavender", 0xB48395),
            new ColorName("English red", 0xAB4B52),
            new ColorName("English vermillion", 0xCC474B),
            new ColorName("English violet", 0x563C5C),
            new ColorName("Eton blue", 0x96C8A2),
            new ColorName("Eucalyptus", 0x44D7A8),
            new ColorName("Facebook Blue", 0x39569C),
            new ColorName("Fallow", 0xC19A6B),
            new ColorName("Falu red", 0x801818),
            new ColorName("Fandango", 0xB53389),
            new ColorName("Fandango pink", 0xDE5285),
            new ColorName("Fashion fuchsia", 0xF400A1),
            new ColorName("Fawn", 0xE5AA70),
            new ColorName("Feldgrau", 0x4D5D53),
            new ColorName("Feldspar", 0xFDD5B1),
            new ColorName("Fern green", 0x4F7942),
            new ColorName("Ferrari red", 0xFF2800),
            new ColorName("Field drab", 0x6C541E),
            new ColorName("Fiery rose", 0xFF5470),
            new ColorName("Firebrick", 0xB22222),
            new ColorName("Fire engine red", 0xCE2029),
            new ColorName("Fire opal", 0xE95C4B),
            new ColorName("Flame", 0xE25822),
            new ColorName("Flamingo pink", 0xFC8EAC),
            new ColorName("Flattery", 0x6B4423),
            new ColorName("Flavescent", 0xF7E98E),
            new ColorName("Flax", 0xEEDC82),
            new ColorName("Flesh", 0xFFE9D1),
            new ColorName("Flickr Blue", 0x216BD6),
            new ColorName("Flickr Pink", 0xFB0081),
            new ColorName("Flirt", 0xA2006D),
            new ColorName("Floral white", 0xFFFAF0),
            new ColorName("Flower girl", 0xF498AD),
            new ColorName("Fluorescent blue", 0x15F4EE),
            new ColorName("Fluorescent orange", 0xFFBF00),
            new ColorName("Fluorescent pink", 0xFF1493),
            new ColorName("Fluorescent yellow", 0xCCFF00),
            new ColorName("Folly", 0xFF004F),
            new ColorName("Forest green (Crayola)", 0x5FA777),
            new ColorName("Forest green (traditional)", 0x014421),
            new ColorName("Forest green (web)", 0x228B22),
            new ColorName("French beige", 0xA67B5B),
            new ColorName("French bistre", 0x856D4D),
            new ColorName("French blue", 0x0072BB),
            new ColorName("French fuchsia", 0xFD3F92),
            new ColorName("French lilac", 0x86608E),
            new ColorName("French lime", 0x9EFD38),
            new ColorName("French mauve", 0xD473D4),
            new ColorName("French pink", 0xFD6C9E),
            new ColorName("French plum", 0x811453),
            new ColorName("French puce", 0x4E1609),
            new ColorName("French raspberry", 0xC72C48),
            new ColorName("French rose", 0xF64A8A),
            new ColorName("French sky blue", 0x77B5FE),
            new ColorName("French violet", 0x8806CE),
            new ColorName("French wine", 0xAC1E44),
            new ColorName("Fresh Air", 0xA6E7FF),
            new ColorName("Frostbite", 0xE936A7),
            new ColorName("Fuchsia", 0xFF00FF),
            new ColorName("Fuchsia (Crayola)", 0xC154C1),
            new ColorName("Fuchsia pink", 0xFF77FF),
            new ColorName("Fuchsia purple", 0xCC397B),
            new ColorName("Fuchsia rose", 0xC74375),
            new ColorName("Fulvous", 0xE48400),
            new ColorName("Fuzzy Wuzzy", 0xCC6666),
            new ColorName("Gamboge", 0xE49B0F),
            new ColorName("Gamboge orange (brown)", 0x996600),
            new ColorName("Garnet", 0x733635),
            new ColorName("Gargoyle Gas", 0xFFDF46),
            new ColorName("Generic viridian", 0x007F66),
            new ColorName("Ghost white", 0xF8F8FF),
            new ColorName("Giant's Club", 0xB05C52),
            new ColorName("Giants orange", 0xFE5A1D),
            new ColorName("Gin", 0xD8E4BC),
            new ColorName("Glaucous", 0x6082B6),
            new ColorName("Glossy grape", 0xAB92B3),
            new ColorName("GO green", 0x00AB66),
            new ColorName("Gold", 0xA57C00),
            new ColorName("Gold (metallic)", 0xD4AF37),
            new ColorName("Gold (web) (Golden)", 0xFFD700),
            new ColorName("Gold (Crayola)", 0xE6BE8A),
            new ColorName("Gold Fusion", 0x85754E),
            new ColorName("Gold foil", 0xBD9B16),
            new ColorName("Golden brown", 0x996515),
            new ColorName("Golden poppy", 0xFCC200),
            new ColorName("Golden yellow", 0xFFDF00),
            new ColorName("Goldenrod", 0xDAA520),
            new ColorName("Google Chrome red", 0xDE5246),
            new ColorName("Google Chrome blue", 0x4C8BF5),
            new ColorName("Google Chrome green", 0x1AA260),
            new ColorName("Google Chrome yellow", 0xFFCE44),
            new ColorName("Granite gray", 0x676767),
            new ColorName("Granny Smith apple", 0xA8E4A0),
            new ColorName("Grape", 0x6F2DA8),
            new ColorName("Gray (HTML/CSS gray)", 0x808080),
            new ColorName("Gray (X11 gray)", 0xBEBEBE),
            new ColorName("Gray-asparagus", 0x465945),
            new ColorName("Gray-blue", 0x8C92AC),
            new ColorName("Green", 0x008001),
            new ColorName("Green (Color Wheel) (X11 green)", 0x00FF00),
            new ColorName("Green (Crayola)", 0x1CAC78),
            new ColorName("Green (HTML/CSS color)", 0x008000),
            new ColorName("Green (Munsell)", 0x00A877),
            new ColorName("Green (NCS)", 0x009F6B),
            new ColorName("Green (Pantone)", 0x00AD43),
            new ColorName("Green (pigment)", 0x00A550),
            new ColorName("Green (RYB)", 0x66B032),
            new ColorName("Green-blue", 0x1164B4),
            new ColorName("Green-blue (Crayola)", 0x2887C8),
            new ColorName("Green Cola", 0x4C721D),
            new ColorName("Green-cyan", 0x009966),
            new ColorName("Green Lizard", 0xA7F432),
            new ColorName("Green Sheen", 0x6EAEA1),
            new ColorName("Green slime", 0x65FF00),
            new ColorName("Green-yellow", 0xADFF2F),
            new ColorName("Green-yellow (Crayola)", 0xF0E891),
            new ColorName("Grullo", 0xA99A86),
            new ColorName("Guppie green", 0x00FF7F),
            new ColorName("Gunmetal", 0x2a3439),
            new ColorName("Guyabano", 0xF8F8F8),
            new ColorName("Halayà úbe", 0x663854),
            new ColorName("Halloween orange", 0xEB6123),
            new ColorName("Han blue", 0x446CCF),
            new ColorName("Han purple", 0x5218FA),
            new ColorName("Hansa yellow", 0xE9D66B),
            new ColorName("Harlequin", 0x3FFF00),
            new ColorName("Harlequin green", 0x46CB18),
            new ColorName("Harmonious rose", 0xF29CB7),
            new ColorName("Harvard crimson", 0xC90016),
            new ColorName("Harvest gold", 0xDA9100),
            new ColorName("Hawaii blue", 0x00C3E3),
            new ColorName("Heart gold", 0x808000),
            new ColorName("Heat Wave", 0xFF7A00),
            new ColorName("Heidelberg red[2]", 0x960018),
            new ColorName("Heliotrope", 0xDF73FF),
            new ColorName("Heliotrope gray", 0xAA98A9),
            new ColorName("Heliotrope magenta", 0xAA00BB),
            new ColorName("Hollywood cerise", 0xF400A1),
            new ColorName("Honeydew", 0xF0FFF0),
            new ColorName("Honolulu blue", 0x006DB0),
            new ColorName("Hooker's green", 0x49796B),
            new ColorName("Hot magenta", 0xFF1DCE),
            new ColorName("Hot pink", 0xFF69B4),
            new ColorName("Huawei Red", 0xCF0A2C),
            new ColorName("Huawei Red (1987-2018)", 0xED1C24),
            new ColorName("Hunter green", 0x355E3B),
            new ColorName("Iceberg", 0x71A6D2),
            new ColorName("Iced tea", 0x923C01),
            new ColorName("Icterine", 0xFCF75E),
            new ColorName("Iguana green", 0x71BC78),
            new ColorName("Illuminating emerald", 0x319177),
            new ColorName("Imperial", 0x602F6B),
            new ColorName("Imperial blue", 0x002395),
            new ColorName("Imperial purple", 0x66023C),
            new ColorName("Imperial red", 0xED2939),
            new ColorName("Inchworm", 0xB2EC5D),
            new ColorName("Independence", 0x4C516D),
            new ColorName("India green", 0x138808),
            new ColorName("Indian red", 0xCD5C5C),
            new ColorName("Indian yellow", 0xE3A857),
            new ColorName("Indigo", 0x4B0082),
            new ColorName("Indigo blue", 0x00416A),
            new ColorName("Indigo dye", 0x091F92),
            new ColorName("Indigo (rainbow)", 0x233067),
            new ColorName("Infra red", 0xFF496C),
            new ColorName("Interdimensional blue", 0x360CCC),
            new ColorName("International Klein Blue", 0x002FA7),
            new ColorName("International orange (aerospace)", 0xFF4F00),
            new ColorName("International orange (engineering)", 0xBA160C),
            new ColorName("International orange (Golden Gate Bridge)", 0xC0362C),
            new ColorName("Iris", 0x5A4FCF),
            new ColorName("Iron", 0xA19D94),
            new ColorName("Irresistible", 0xB3446C),
            new ColorName("Isabelline", 0xF4F0EC),
            new ColorName("Islamic green", 0x009000),
            new ColorName("Italian ice", 0xE9F6EF),
            new ColorName("Italian leather", 0x635A52),
            new ColorName("Italian roast", 0x906652),
            new ColorName("Italian sky blue", 0xB2FFFF),
            new ColorName("Ivory", 0xFFFFF0),
            new ColorName("Jacarta", 0x3D325D),
            new ColorName("Jacko bean", 0x413628),
            new ColorName("Jade", 0x00A86B),
            new ColorName("Japanese carmine", 0x9D2933),
            new ColorName("Japanese indigo", 0x264348),
            new ColorName("Japanese laurel", 0x2F7532),
            new ColorName("Japanese violet", 0x5B3256),
            new ColorName("Jasmine", 0xF8DE7E),
            new ColorName("Jasper", 0xD73B3E),
            new ColorName("Jasper orange", 0xDE8F4E),
            new ColorName("Jazzberry jam", 0xA50B5E),
            new ColorName("Jelly bean", 0xDA614E),
            new ColorName("Jelly bean blue", 0x44798E),
            new ColorName("Jet", 0x343434),
            new ColorName("Jet stream", 0xBBD0C9),
            new ColorName("Jonquil", 0xF4CA16),
            new ColorName("Jordy blue", 0x8AB9F1),
            new ColorName("June bud", 0xBDDA57),
            new ColorName("Jungle green", 0x29AB87),
            new ColorName("Kelly green", 0x4CBB17),
            new ColorName("Kenyan copper", 0x7C1C05),
            new ColorName("Keppel", 0x3AB09E),
            new ColorName("Key lime", 0xE8F48C),
            new ColorName("Khaki (HTML/CSS) (Khaki)", 0xC3B091),
            new ColorName("Khaki (X11) (Light khaki)", 0xF0E68C),
            new ColorName("Kiwi", 0x8EE53F),
            new ColorName("Kobe", 0x882D17),
            new ColorName("Kobi", 0xE79FC4),
            new ColorName("Kobicha", 0x6B4423),
            new ColorName("Kombu green", 0x354230),
            new ColorName("KSU purple", 0x512888),
            new ColorName("KU crimson", 0xE8000D),
            new ColorName("Kumquat", 0xFB9912),
            new ColorName("La Salle green", 0x087830),
            new ColorName("Languid lavender", 0xD6CADD),
            new ColorName("Lanzones", 0xE0BC5B),
            new ColorName("Lapis lazuli", 0x26619C),
            new ColorName("Laser lemon", 0xFFFF66),
            new ColorName("Laurel green", 0xA9BA9D),
            new ColorName("Lava", 0xCF1020),
            new ColorName("Lavender (floral)", 0xB57EDC),
            new ColorName("Lavender (web)", 0xE6E6FA),
            new ColorName("Lavender blue", 0xCCCCFF),
            new ColorName("Lavender blush", 0xFFF0F5),
            new ColorName("Lavender gray", 0xC4C3D0),
            new ColorName("Lavender indigo", 0x9457EB),
            new ColorName("Lavender magenta", 0xEE82EE),
            new ColorName("Lavender mist", 0xE6E6FA),
            new ColorName("Lavender pink", 0xFBAED2),
            new ColorName("Lavender purple", 0x967BB6),
            new ColorName("Lavender rose", 0xFBA0E3),
            new ColorName("Lawn green", 0x7CFC00),
            new ColorName("Lemon", 0xFFF700),
            new ColorName("Lemon chiffon", 0xFFFACD),
            new ColorName("Lemon curry", 0xCCA01D),
            new ColorName("Lemon glacier", 0xFDFF00),
            new ColorName("Lemon iced tea", 0xBD3000),
            new ColorName("Lemon lime", 0xE3FF00),
            new ColorName("Lemon lime", 0x5CFF67),
            new ColorName("Lemon meringue", 0xF6EABE),
            new ColorName("Lemon yellow", 0xFFF44F),
            new ColorName("Lemon yellow (Crayola)", 0xFFFF9F),
            new ColorName("Lenurple", 0xBA93D8),
            new ColorName("Liberty", 0x545AA7),
            new ColorName("Licorice", 0x1A1110),
            new ColorName("Light apricot", 0xFDD5B1),
            new ColorName("Light blue", 0xADD8E6),
            new ColorName("Light brown", 0xB5651D),
            new ColorName("Light carmine pink", 0xE66771),
            new ColorName("Light chocolate cosmos", 0x551F2F),
            new ColorName("Light cobalt blue", 0x88ACE0),
            new ColorName("Light coral", 0xF08080),
            new ColorName("Light cornflower blue", 0x93CCEA),
            new ColorName("Light crimson", 0xF56991),
            new ColorName("Light cyan", 0xE0FFFF),
            new ColorName("Light deep pink", 0xFF5CCD),
            new ColorName("Light French beige", 0xC8AD7F),
            new ColorName("Light fuchsia pink", 0xF984EF),
            new ColorName("Light gold", 0xB29700),
            new ColorName("Light goldenrod yellow", 0xFAFAD2),
            new ColorName("Light gray", 0xD3D3D3),
            new ColorName("Light grayish magenta", 0xCC99CC),
            new ColorName("Light green", 0x90EE90),
            new ColorName("Light hot pink", 0xFFB3DE),
            new ColorName("Light khaki", 0xF0E68C),
            new ColorName("Light magenta", 0xFF80FF),
            new ColorName("Light medium orchid", 0xD39BCB),
            new ColorName("Light moss green", 0xADDFAD),
            new ColorName("Light orange", 0xFED8B1),
            new ColorName("Light orchid", 0xE6A8D7),
            new ColorName("Light pastel purple", 0xB19CD9),
            new ColorName("Light periwinkle", 0xC5CBE1),
            new ColorName("Light pink", 0xFFB6C1),
            new ColorName("Light red", 0xFFCCCB),
            new ColorName("Light red ochre", 0xE97451),
            new ColorName("Light salmon", 0xFFA07A),
            new ColorName("Light salmon pink", 0xFF9999),
            new ColorName("Light sea green", 0x20B2AA),
            new ColorName("Light silver", 0xD8D8D8),
            new ColorName("Light sky blue", 0x87CEFA),
            new ColorName("Light slate gray", 0x778899),
            new ColorName("Light steel blue", 0xB0C4DE),
            new ColorName("Light taupe", 0xB38B6D),
            new ColorName("Light Thulian pink", 0xE68FAC),
            new ColorName("Light yellow", 0xFFFFE0),
            new ColorName("Lilac", 0xC8A2C8),
            new ColorName("Lilac Luster", 0xAE98AA),
            new ColorName("Lime (color wheel)", 0xBFFF00),
            new ColorName("Lime (web) (X11 green)", 0x00FF00),
            new ColorName("Lime green", 0x32CD32),
            new ColorName("Limerick", 0x9DC209),
            new ColorName("Lincoln green", 0x195905),
            new ColorName("Linen", 0xFAF0E6),
            new ColorName("Linkedin Blue", 0x0072B1),
            new ColorName("Lion", 0xC19A6B),
            new ColorName("Liseran purple", 0xDE6FA1),
            new ColorName("Little boy blue", 0x6CA0DC),
            new ColorName("Little girl pink", 0xF8B9D4),
            new ColorName("Liver", 0x674C47),
            new ColorName("Liver (dogs)", 0xB86D29),
            new ColorName("Liver (organ)", 0x6C2E1F),
            new ColorName("Liver chestnut", 0x987456),
            new ColorName("Livid", 0x6699CC),
            new ColorName("Lotion", 0xFEFDFA),
            new ColorName("Lotion blue", 0x15F2FD),
            new ColorName("Lotion pink", 0xECCFCF),
            new ColorName("Lumber", 0xFFE4CD),
            new ColorName("Lust", 0xE62020),
            new ColorName("Lychee", 0xDC5349),
            new ColorName("Maastricht blue", 0x001C3D),
            new ColorName("Macaroni and Cheese", 0xFFBD88),
            new ColorName("Madder Lake", 0xCC3336),
            new ColorName("Magenta", 0xFF00FF),
            new ColorName("Magenta (Crayola)", 0xFF55A3),
            new ColorName("Magenta (dye)", 0xCA1F7B),
            new ColorName("Magenta (Pantone)", 0xD0417E),
            new ColorName("Magenta (process)", 0xFF0090),
            new ColorName("Magenta haze", 0x9F4576),
            new ColorName("Magenta-pink", 0xCC338B),
            new ColorName("Magic mint", 0xAAF0D1),
            new ColorName("Magic Potion", 0xFF4466),
            new ColorName("Magnolia", 0xF8F4FF),
            new ColorName("Mahogany", 0xC04000),
            new ColorName("Maize", 0xFBEC5D),
            new ColorName("Maize (Crayola)", 0xF2C649),
            new ColorName("Majorelle blue", 0x6050DC),
            new ColorName("Malachite", 0x0BDA51),
            new ColorName("Manatee", 0x979AAA),
            new ColorName("Mandarin", 0xF37A48),
            new ColorName("Mango", 0xFDBE02),
            new ColorName("Mango green", 0x96FF00),
            new ColorName("Mango Tango", 0xFF8243),
            new ColorName("Mantis", 0x74C365),
            new ColorName("Mardi Gras", 0x880085),
            new ColorName("Marigold", 0xEAA221),
            new ColorName("Maroon (Crayola)", 0xC32148),
            new ColorName("Maroon (HTML/CSS)", 0x800000),
            new ColorName("Maroon (X11)", 0xB03060),
            new ColorName("Mauve", 0xE0B0FF),
            new ColorName("Mauve taupe", 0x915F6D),
            new ColorName("Mauvelous", 0xEF98AA),
            new ColorName("Maximum blue", 0x47ABCC),
            new ColorName("Maximum blue green", 0x30BFBF),
            new ColorName("Maximum blue purple", 0xACACE6),
            new ColorName("Maximum green", 0x5E8C31),
            new ColorName("Maximum green yellow", 0xD9E650),
            new ColorName("Maximum orange", 0xFF5B00),
            new ColorName("Maximum purple", 0x733380),
            new ColorName("Maximum red", 0xD92121),
            new ColorName("Maximum red purple", 0xA63A79),
            new ColorName("Maximum yellow", 0xFAFA37),
            new ColorName("Maximum yellow red", 0xF2BA49),
            new ColorName("May green", 0x4C9141),
            new ColorName("Maya blue", 0x73C2FB),
            new ColorName("Meat brown", 0xE5B73B),
            new ColorName("Medium aquamarine", 0x66DDAA),
            new ColorName("Medium blue", 0x0000CD),
            new ColorName("Medium candy apple red", 0xE2062C),
            new ColorName("Medium carmine", 0xAF4035),
            new ColorName("Medium champagne", 0xF3E5AB),
            new ColorName("Medium electric blue", 0x035096),
            new ColorName("Medium jungle green", 0x1C352D),
            new ColorName("Medium lavender magenta", 0xDDA0DD),
            new ColorName("Medium orchid", 0xBA55D3),
            new ColorName("Medium Persian blue", 0x0067A5),
            new ColorName("Medium purple", 0x9370DB),
            new ColorName("Medium red-violet", 0xBB3385),
            new ColorName("Medium ruby", 0xAA4069),
            new ColorName("Medium sea green", 0x3CB371),
            new ColorName("Medium sky blue", 0x80DAEB),
            new ColorName("Medium slate blue", 0x7B68EE),
            new ColorName("Medium spring bud", 0xC9DC87),
            new ColorName("Medium spring green", 0x00FA9A),
            new ColorName("Medium taupe", 0x674C47),
            new ColorName("Medium turquoise", 0x48D1CC),
            new ColorName("Medium Tuscan red", 0x79443B),
            new ColorName("Medium vermilion", 0xD9603B),
            new ColorName("Medium violet-red", 0xC71585),
            new ColorName("Mellow apricot", 0xF8B878),
            new ColorName("Mellow yellow", 0xF8DE7E),
            new ColorName("Melancholy", 0xFDBCB4),
            new ColorName("Melon", 0xFEBAAD),
            new ColorName("Menthol", 0xC1F9A2),
            new ColorName("Metallic blue", 0x32527B),
            new ColorName("Metallic bronze", 0xA97142),
            new ColorName("Metallic brown", 0xAC4313),
            new ColorName("Metallic gold", 0xD3AF37),
            new ColorName("Metallic green", 0x296E01),
            new ColorName("Metallic orange", 0xDA680F),
            new ColorName("Metallic pink", 0xEDA6C4),
            new ColorName("Metallic red", 0xA62C2B),
            new ColorName("Metallic Seaweed", 0x0A7E8C),
            new ColorName("Metallic silver", 0xA8A9AD),
            new ColorName("Metallic Sunburst", 0x9C7C38),
            new ColorName("Metallic violet", 0x5B0A91),
            new ColorName("Metallic yellow", 0xFDCC0D),
            new ColorName("Mexican pink", 0xE4007C),
            new ColorName("Microsoft red", 0xF04E1F),
            new ColorName("Microsoft blue", 0x00A2ED),
            new ColorName("Microsoft green", 0x7DB700),
            new ColorName("Microsoft yellow", 0xFDB900),
            new ColorName("Microsoft Edge blue", 0x0078D7),
            new ColorName("Middle blue", 0x7ED4E6),
            new ColorName("Middle blue green", 0x8DD9CC),
            new ColorName("Middle blue purple", 0x8B72BE),
            new ColorName("Middle grey", 0x8B8680),
            new ColorName("Middle green", 0x4D8C57),
            new ColorName("Middle green yellow", 0xACBF60),
            new ColorName("Middle purple", 0xD982B5),
            new ColorName("Middle red", 0xE58E73),
            new ColorName("Middle red purple", 0xA55353),
            new ColorName("Middle yellow", 0xFFEB00),
            new ColorName("Middle yellow red", 0xECB176),
            new ColorName("Midnight", 0x702670),
            new ColorName("Midnight blue", 0x191970),
            new ColorName("Midnight blue", 0x00468C),
            new ColorName("Midnight green (eagle green)", 0x004953),
            new ColorName("Mikado yellow", 0xFFC40C),
            new ColorName("Milk", 0xFDFFF5),
            new ColorName("Milk chocolate", 0x84563C),
            new ColorName("Mimi pink", 0xFFDAE9),
            new ColorName("Mindaro", 0xE3F988),
            new ColorName("Ming", 0x36747D),
            new ColorName("Minion yellow", 0xF5E050),
            new ColorName("Mint", 0x3EB489),
            new ColorName("Mint cream", 0xF5FFFA),
            new ColorName("Mint green", 0x98FF98),
            new ColorName("Misty moss", 0xBBB477),
            new ColorName("Misty rose", 0xFFE4E1),
            new ColorName("Moccasin", 0xFAEBD7),
            new ColorName("Mocha", 0xBEA493),
            new ColorName("Mode beige", 0x967117),
            new ColorName("Moonstone", 0x3AA8C1),
            new ColorName("Moonstone blue", 0x73A9C2),
            new ColorName("Mordant red 19", 0xAE0C00),
            new ColorName("Morning blue", 0x8DA399),
            new ColorName("Moss green", 0x8A9A5B),
            new ColorName("Mountain Meadow", 0x30BA8F),
            new ColorName("Mountbatten pink", 0x997A8D),
            new ColorName("MSU green", 0x18453B),
            new ColorName("Mud", 0x70543E),
            new ColorName("Mughal green", 0x306030),
            new ColorName("Mulberry", 0xC54B8C),
            new ColorName("Mulberry (Crayola)", 0xC8509B),
            new ColorName("Mummy's Tomb", 0x828E84),
            new ColorName("Mustard", 0xFFDB58),
            new ColorName("Mustard brown", 0xCD7A00),
            new ColorName("Mustard green", 0x6E6E30),
            new ColorName("Mustard yellow", 0xE1AD01),
            new ColorName("Myrtle green", 0x317873),
            new ColorName("Mystic", 0xD65282),
            new ColorName("Mystic maroon", 0xAD4379),
            new ColorName("Mystic red", 0xFF5500),
            new ColorName("Nachos", 0xF7CE2A),
            new ColorName("Nadeshiko pink", 0xF6ADC6),
            new ColorName("Napier green", 0x2A8000),
            new ColorName("Naples yellow", 0xFADA5E),
            new ColorName("Navajo white", 0xFFDEAD),
            new ColorName("Navy blue", 0x000080),
            new ColorName("Navy blue (Crayola)", 0x1974D2),
            new ColorName("Neon blue", 0x1B03A3),
            new ColorName("Neon green", 0x39FF14),
            new ColorName("New Car", 0x214FC6),
            new ColorName("New York pink", 0xD7837F),
            new ColorName("Nickel", 0x727472),
            new ColorName("Nintendo red", 0xE4000F),
            new ColorName("Non-photo blue", 0xA4DDED),
            new ColorName("North Texas green", 0x059033),
            new ColorName("Nyanza", 0xE9FFDB),
            new ColorName("Ocean Blue", 0x4F42B5),
            new ColorName("Ocean boat blue", 0x0077BE),
            new ColorName("Ocean green", 0x48BF91),
            new ColorName("Ochre", 0xCC7722),
            new ColorName("Office green", 0x008000),
            new ColorName("Ogre Odor", 0xFD5240),
            new ColorName("Old burgundy", 0x43302E),
            new ColorName("Old gold", 0xCFB53B),
            new ColorName("Old heliotrope", 0x563C5C),
            new ColorName("Old lace", 0xFDF5E6),
            new ColorName("Old lavender", 0x796878),
            new ColorName("Old mauve", 0x673147),
            new ColorName("Old moss green", 0x867E36),
            new ColorName("Old rose", 0xC08081),
            new ColorName("Old silver", 0x848482),
            new ColorName("Olive", 0x808000),
            new ColorName("Olive Drab", 0x6B8E23),
            new ColorName("Olive green", 0xB5B35C),
            new ColorName("Olivine", 0x9AB973),
            new ColorName("Onyx", 0x353839),
            new ColorName("Opal", 0xA8C3BC),
            new ColorName("Opera Red", 0xFF1B2D),
            new ColorName("Opera mauve", 0xB784A7),
            new ColorName("Orange", 0xFF6600),
            new ColorName("Orange (color wheel)", 0xFF7F00),
            new ColorName("Orange (Crayola)", 0xFF7538),
            new ColorName("Orange (Pantone)", 0xFF5800),
            new ColorName("Orange (RYB)", 0xFB9902),
            new ColorName("Orange (web)", 0xFFA500),
            new ColorName("Orange peel", 0xFF9F00),
            new ColorName("Orange-red", 0xFF681F),
            new ColorName("Orange-red (Crayola)", 0xFF5349),
            new ColorName("Orange soda", 0xFA5B3D),
            new ColorName("Orange soda", 0xEB593D),
            new ColorName("Orange-yellow", 0xF5BD1F),
            new ColorName("Orange-yellow (Crayola)", 0xF8D568),
            new ColorName("Orchid", 0xDA70D6),
            new ColorName("Orchid pink", 0xF2BDCD),
            new ColorName("Orchid (Crayola)", 0xE29CD2),
            new ColorName("Orioles orange", 0xFB4F14),
            new ColorName("Otter brown", 0x654321),
            new ColorName("Outer space", 0x414A4C),
            new ColorName("Outer space (Crayola)", 0x2D383A),
            new ColorName("Outrageous Orange", 0xFF6E4A),
            new ColorName("Oxblood", 0x800020),
            new ColorName("Oxford blue", 0x002147),
            new ColorName("Oxley", 0x6D9A79),
            new ColorName("OU Crimson red", 0x841617),
            new ColorName("Pacific blue", 0x1CA9C9),
            new ColorName("Painite", 0x6B4947),
            new ColorName("Pakistan green", 0x006600),
            new ColorName("Palatinate blue", 0x273BE2),
            new ColorName("Palatinate purple", 0x682860),
            new ColorName("Pale aqua", 0xBCD4E6),
            new ColorName("Pale blue", 0xAFEEEE),
            new ColorName("Pale brown", 0x987654),
            new ColorName("Pale carmine", 0xAF4035),
            new ColorName("Pale cerulean", 0x9BC4E2),
            new ColorName("Pale chestnut", 0xDDADAF),
            new ColorName("Pale copper", 0xDA8A67),
            new ColorName("Pale cornflower blue", 0xABCDEF),
            new ColorName("Pale cyan", 0x87D3F8),
            new ColorName("Pale gold", 0xE6BE8A),
            new ColorName("Pale goldenrod", 0xEEE8AA),
            new ColorName("Pale green", 0x98FB98),
            new ColorName("Pale lavender", 0xDCD0FF),
            new ColorName("Pale magenta", 0xF984E5),
            new ColorName("Pale magenta-pink", 0xFF99CC),
            new ColorName("Pale pink", 0xFADADD),
            new ColorName("Pale plum", 0xDDA0DD),
            new ColorName("Pale purple (Pantone)", 0xFAE6FA),
            new ColorName("Pale red-violet", 0xDB7093),
            new ColorName("Pale robin egg blue", 0x96DED1),
            new ColorName("Pale silver", 0xC9C0BB),
            new ColorName("Pale spring bud", 0xECEBBD),
            new ColorName("Pale taupe", 0xBC987E),
            new ColorName("Pale turquoise", 0xAFEEEE),
            new ColorName("Pale violet", 0xCC99FF),
            new ColorName("Pale violet-red", 0xDB7093),
            new ColorName("Palm Leaf", 0x6F9940),
            new ColorName("Panasonic blue", 0x0040BE),
            new ColorName("Pansy purple", 0x78184A),
            new ColorName("Paolo Veronese green", 0x009B7D),
            new ColorName("Papaya whip", 0xFFEFD5),
            new ColorName("Parakeet Blue", 0x7EB6FF),
            new ColorName("Paradise pink", 0xE63E62),
            new ColorName("Paris Green", 0x50C878),
            new ColorName("Parrot Pink", 0xD998A0),
            new ColorName("Pastel blue", 0xAEC6CF),
            new ColorName("Pastel brown", 0x836953),
            new ColorName("Pastel gray", 0xCFCFC4),
            new ColorName("Pastel green", 0x77DD77),
            new ColorName("Pastel magenta", 0xF49AC2),
            new ColorName("Pastel orange", 0xFFB347),
            new ColorName("Pastel pink", 0xDEA5A4),
            new ColorName("Pastel purple", 0xB39EB5),
            new ColorName("Pastel red", 0xFF6961),
            new ColorName("Pastel violet", 0xCB99C9),
            new ColorName("Pastel yellow", 0xFDFD96),
            new ColorName("Patriarch", 0x800080),
            new ColorName("Payne's grey", 0x536878),
            new ColorName("Peach", 0xFFE5B4),
            new ColorName("Peach", 0xFFCBA4),
            new ColorName("Peach-orange", 0xFFCC99),
            new ColorName("Peach puff", 0xFFDAB9),
            new ColorName("Peach Burst", 0xF39998),
            new ColorName("Peach-yellow", 0xFADFAD),
            new ColorName("Pear", 0xD1E231),
            new ColorName("Pearl", 0xEAE0C8),
            new ColorName("Pearl Aqua", 0x88D8C0),
            new ColorName("Pearly purple", 0xB768A2),
            new ColorName("Penguin White", 0xF5F3EF),
            new ColorName("Peridot", 0xE6E200),
            new ColorName("Periwinkle", 0xCCCCFF),
            new ColorName("Periwinkle (Crayola)", 0xC3CDE6),
            new ColorName("Permanent Geranium Lake", 0xE12C2C),
            new ColorName("Persian blue", 0x1C39BB),
            new ColorName("Persian green", 0x00A693),
            new ColorName("Persian indigo", 0x32127A),
            new ColorName("Persian orange", 0xD99058),
            new ColorName("Persian pink", 0xF77FBE),
            new ColorName("Persian plum", 0x701C1C),
            new ColorName("Persian red", 0xCC3333),
            new ColorName("Persian rose", 0xFE28A2),
            new ColorName("Persimmon", 0xEC5800),
            new ColorName("Peru", 0xCD853F),
            new ColorName("Pewter Blue", 0x8BA8B7),
            new ColorName("Philippine blue", 0x0038A7),
            new ColorName("Philippine bronze", 0x6E3A07),
            new ColorName("Philippine brown", 0x5D1916),
            new ColorName("Philippine gold", 0xB17304),
            new ColorName("Philippine golden yellow", 0xFFDF00),
            new ColorName("Philippine gray", 0x8C8C8C),
            new ColorName("Philippine green", 0x008543),
            new ColorName("Philippine orange", 0xFF7300),
            new ColorName("Philippine pink", 0xFA1A8E),
            new ColorName("Philippine red", 0xCE1127),
            new ColorName("Philippine silver", 0xB3B3B3),
            new ColorName("Philippine violet", 0x81007F),
            new ColorName("Philippine yellow", 0xFECB00),
            new ColorName("Phlox", 0xDF00FF),
            new ColorName("Phthalo blue", 0x000F89),
            new ColorName("Phthalo green", 0x123524),
            new ColorName("Picton blue", 0x45B1E8),
            new ColorName("Pictorial carmine", 0xC30B4E),
            new ColorName("Piggy pink", 0xFDDDE6),
            new ColorName("Pine green", 0x01796F),
            new ColorName("Pine tree", 0x2A2F23),
            new ColorName("Pineapple", 0x563C0D),
            new ColorName("Pink", 0xFFC0CB),
            new ColorName("Pink (Pantone)", 0xD74894),
            new ColorName("Pink Diamond (Ace Hardware Color)", 0xF6D6DE),
            new ColorName("Pink Diamond (Independent Retailers Colors)", 0xF0D3DC),
            new ColorName("Pink flamingo", 0xFC74FD),
            new ColorName("Pink lace", 0xFFDDF4),
            new ColorName("Pink lavender", 0xD8B2D1),
            new ColorName("Pink-orange", 0xFF9966),
            new ColorName("Pink pearl", 0xE7ACCF),
            new ColorName("Pink raspberry", 0x980036),
            new ColorName("Pink Sherbet", 0xF78FA7),
            new ColorName("Pistachio", 0x93C572),
            new ColorName("Pixie Powder", 0x391285),
            new ColorName("Platinum", 0xE5E4E2),
            new ColorName("Plum", 0x8E4585),
            new ColorName("Plum (web)", 0xDDA0DD),
            new ColorName("Plump Purple", 0x5946B2),
            new ColorName("Poker Green", 0x35654D),
            new ColorName("Police blue", 0x374F6B),
            new ColorName("Polished Pine", 0x5DA493),
            new ColorName("Pomegranate", 0x660C21),
            new ColorName("Pomelo", 0x96A53C),
            new ColorName("Pomelo White", 0xF9FFE3),
            new ColorName("Pomelo Olive", 0xBFBD70),
            new ColorName("Pomp and Power", 0x86608E),
            new ColorName("Poppy Petal", 0xF6A08C),
            new ColorName("Popstar", 0xBE4F62),
            new ColorName("Portland Orange", 0xFF5A36),
            new ColorName("Porcupine", 0x936900),
            new ColorName("Powder blue", 0xB0E0E6),
            new ColorName("Princess Perfume", 0xFF85CF),
            new ColorName("Princeton orange", 0xF58025),
            new ColorName("Prune", 0x701C1C),
            new ColorName("Prussian blue", 0x003153),
            new ColorName("Psychedelic purple", 0xDF00FF),
            new ColorName("Puce", 0xCC8899),
            new ColorName("Puce red", 0x722F37),
            new ColorName("Pullman Brown (UPS Brown)", 0x644117),
            new ColorName("Pullman Green", 0x3B331C),
            new ColorName("Pumpkin", 0xFF7518),
            new ColorName("Purple", 0x6A0DAD),
            new ColorName("Purple (HTML)", 0x800080),
            new ColorName("Purple (Munsell)", 0x9F00C5),
            new ColorName("Purple (X11)", 0xA020F0),
            new ColorName("Purple Heart", 0x69359C),
            new ColorName("Purple mountain majesty", 0x9678B6),
            new ColorName("Purple navy", 0x4E5180),
            new ColorName("Purple pizzazz", 0xFE4EDA),
            new ColorName("Purple Plum", 0x9C51B6),
            new ColorName("Purple taupe", 0x50404D),
            new ColorName("Purpureus", 0x9A4EAE),
            new ColorName("Quartz", 0x51484F),
            new ColorName("Queen blue", 0x436B95),
            new ColorName("Queen pink", 0xE8CCD7),
            new ColorName("Quick Silver", 0xA6A6A6),
            new ColorName("Quinacridone magenta", 0x8E3A59),
            new ColorName("Quincy", 0x6A5445),
            new ColorName("Rackley", 0x5D8AA8),
            new ColorName("Radical Red", 0xFF355E),
            new ColorName("Raisin black", 0x242124),
            new ColorName("Rajah", 0xFBAB60),
            new ColorName("Rambutan", 0xC71232),
            new ColorName("Rambutan Red", 0xA72127),
            new ColorName("Raspberry", 0xE30B5D),
            new ColorName("Raspberry glace", 0x915F6D),
            new ColorName("Raspberry pink", 0xE25098),
            new ColorName("Raspberry rose", 0xB3446C),
            new ColorName("Raw Sienna", 0xD68A59),
            new ColorName("Raw umber", 0x826644),
            new ColorName("Razzle dazzle rose", 0xFF33CC),
            new ColorName("Razzmatazz", 0xE3256B),
            new ColorName("Razzmic Berry", 0x8D4E85),
            new ColorName("Rebecca Purple", 0x663399),
            new ColorName("Red", 0xFF0000),
            new ColorName("Red (Crayola)", 0xEE204D),
            new ColorName("Red (Munsell)", 0xF2003C),
            new ColorName("Red (NCS)", 0xC40233),
            new ColorName("Red (Pantone)", 0xED2939),
            new ColorName("Red (pigment)", 0xED1C24),
            new ColorName("Red (RYB)", 0xFE2712),
            new ColorName("Red-brown", 0xA52A2A),
            new ColorName("Red cola", 0xB62020),
            new ColorName("Red devil", 0x860111),
            new ColorName("Red-orange", 0xFF5349),
            new ColorName("Red-orange (Crayola)", 0xFF681F),
            new ColorName("Red-orange (Color wheel)", 0xFF4500),
            new ColorName("Red-purple", 0xE40078),
            new ColorName("Red Salsa", 0xFD3A4A),
            new ColorName("Red-violet", 0xC71585),
            new ColorName("Red-violet (Crayola)", 0xC0448F),
            new ColorName("Red-violet (Color wheel)", 0x922B3E),
            new ColorName("Redwood", 0xA45A52),
            new ColorName("Regalia", 0x522D80),
            new ColorName("Registration black", 0x000000),
            new ColorName("Resolution blue", 0x002387),
            new ColorName("Rhythm", 0x777696),
            new ColorName("Rich black", 0x004040),
            new ColorName("Rich black (FOGRA29)", 0x010B13),
            new ColorName("Rich black (FOGRA39)", 0x010203),
            new ColorName("Rich brilliant lavender", 0xF1A7FE),
            new ColorName("Rich carmine", 0xD70040),
            new ColorName("Rich electric blue", 0x0892D0),
            new ColorName("Rich lavender", 0xA76BCF),
            new ColorName("Rich lilac", 0xB666D2),
            new ColorName("Rich maroon", 0xB03060),
            new ColorName("Rifle green", 0x444C38),
            new ColorName("Ripe mango", 0xFFC324),
            new ColorName("Roast coffee", 0x704241),
            new ColorName("Robin egg blue", 0x00CCCC),
            new ColorName("Rocket metallic", 0x8A7F80),
            new ColorName("Roman silver", 0x838996),
            new ColorName("Root beer", 0x290E05),
            new ColorName("Rose", 0xFF007F),
            new ColorName("Rose bonbon", 0xF9429E),
            new ColorName("Rose Dust", 0x9E5E6F),
            new ColorName("Rose ebony", 0x674846),
            new ColorName("Rose garnet", 0x960145),
            new ColorName("Rose gold", 0xB76E79),
            new ColorName("Rose madder", 0xE32636),
            new ColorName("Rose pink", 0xFF66CC),
            new ColorName("Rose quartz", 0xAA98A9),
            new ColorName("Rose quartz pink", 0xBD559C),
            new ColorName("Rose red", 0xC21E56),
            new ColorName("Rose taupe", 0x905D5D),
            new ColorName("Rose vale", 0xAB4E52),
            new ColorName("Rosewood", 0x65000B),
            new ColorName("Rosso corsa", 0xD40000),
            new ColorName("Rosy brown", 0xBC8F8F),
            new ColorName("Royal azure", 0x0038A8),
            new ColorName("Royal blue (dark)", 0x002366),
            new ColorName("Royal blue (light)", 0x4169E1),
            new ColorName("Royal brown", 0x523B35),
            new ColorName("Royal fuchsia", 0xCA2C92),
            new ColorName("Royal green", 0x136207),
            new ColorName("Royal orange", 0xF99245),
            new ColorName("Royal pink", 0xE73895),
            new ColorName("Royal red", 0x9B1C31),
            new ColorName("Royal red", 0xD00060),
            new ColorName("Royal purple", 0x7851A9),
            new ColorName("Royal yellow", 0xFADA5E),
            new ColorName("Ruber", 0xCE4676),
            new ColorName("Rubine red", 0xD10056),
            new ColorName("Ruby", 0xE0115F),
            new ColorName("Ruby red", 0x9B111E),
            new ColorName("Ruddy", 0xFF0028),
            new ColorName("Ruddy brown", 0xBB6528),
            new ColorName("Ruddy pink", 0xE18E96),
            new ColorName("Rufous", 0xA81C07),
            new ColorName("Russet", 0x80461B),
            new ColorName("Russian green", 0x679267),
            new ColorName("Russian violet", 0x32174D),
            new ColorName("Rust", 0xB7410E),
            new ColorName("Rusty red", 0xDA2C43),
            new ColorName("Sacramento State green", 0x043927),
            new ColorName("Saddle brown", 0x8B4513),
            new ColorName("Safety orange", 0xFF7800),
            new ColorName("Safety orange (blaze orange)", 0xFF6700),
            new ColorName("Safety yellow", 0xEED202),
            new ColorName("Saffron", 0xF4C430),
            new ColorName("Sage", 0xBCB88A),
            new ColorName("St. Patrick's blue", 0x23297A),
            new ColorName("Salem", 0x177B4D),
            new ColorName("Salmon", 0xFA8072),
            new ColorName("Salmon pink", 0xFF91A4),
            new ColorName("Salmon Rose", 0xE7968B),
            new ColorName("Samsung blue", 0x12279E),
            new ColorName("Sand", 0xC2B280),
            new ColorName("Sand dune", 0x967117),
            new ColorName("Sandstorm", 0xECD540),
            new ColorName("Sandy brown", 0xF4A460),
            new ColorName("Sandy Tan", 0xFDD9B5),
            new ColorName("Sandy taupe", 0x967117),
            new ColorName("Sangria", 0x92000A),
            new ColorName("Sap green", 0x507D2A),
            new ColorName("Sapphire", 0x0F52BA),
            new ColorName("Sapphire blue", 0x0067A5),
            new ColorName("Sasquatch Socks", 0xFF4681),
            new ColorName("Satin sheen gold", 0xCBA135),
            new ColorName("Scarlet", 0xFF2400),
            new ColorName("Scarlet", 0xFD0E35),
            new ColorName("Schauss pink", 0xFF91AF),
            new ColorName("School bus yellow", 0xFFD800),
            new ColorName("Screamin' Green", 0x66FF66),
            new ColorName("Sea blue", 0x006994),
            new ColorName("Sea Foam Green", 0x9FE2BF),
            new ColorName("Sea green", 0x2E8B57),
            new ColorName("Sea green (Crayola)", 0x00FFCD),
            new ColorName("Sea Serpent", 0x4BC7CF),
            new ColorName("Seal brown", 0x59260B),
            new ColorName("Seashell", 0xFFF5EE),
            new ColorName("Selective yellow", 0xFFBA00),
            new ColorName("Sepia", 0x704214),
            new ColorName("Sesame Street Green", 0x00A870),
            new ColorName("Shadow", 0x8A795D),
            new ColorName("Shadow blue", 0x778BA5),
            new ColorName("Shampoo", 0xFFCFF1),
            new ColorName("Shamrock green", 0x009E60),
            new ColorName("Shandy", 0xFFE670),
            new ColorName("Sheen green", 0x8FD400),
            new ColorName("Shimmering Blush", 0xD98695),
            new ColorName("Shiny Shamrock", 0x5FA778),
            new ColorName("Shocking pink", 0xFC0FC0),
            new ColorName("Shocking pink (Crayola)", 0xFF6FFF),
            new ColorName("Sienna", 0x882D17),
            new ColorName("Silver", 0xC0C0C0),
            new ColorName("Silver (Crayola)", 0xC9C0BB),
            new ColorName("Silver (Metallic)", 0xAAA9AD),
            new ColorName("Silver chalice", 0xACACAC),
            new ColorName("Silver foil", 0xAFB1AE),
            new ColorName("Silver Lake blue", 0x5D89BA),
            new ColorName("Silver pink", 0xC4AEAD),
            new ColorName("Silver sand", 0xBFC1C2),
            new ColorName("Sinopia", 0xCB410B),
            new ColorName("Sizzling Red", 0xFF3855),
            new ColorName("Sizzling Sunrise", 0xFFDB00),
            new ColorName("Skobeloff", 0x007474),
            new ColorName("Sky blue", 0x87CEEB),
            new ColorName("Sky blue (Crayola)", 0x76D7EA),
            new ColorName("Sky magenta", 0xCF71AF),
            new ColorName("Slate blue", 0x6A5ACD),
            new ColorName("Slate gray", 0x708090),
            new ColorName("Slimy green", 0x299617),
            new ColorName("Smalt (Dark powder blue)", 0x003399),
            new ColorName("Smashed Pumpkin", 0xFF6D3A),
            new ColorName("Smitten", 0xC84186),
            new ColorName("Smoke", 0x738276),
            new ColorName("Smokey Topaz", 0x832A0D),
            new ColorName("Smoky black", 0x100C08),
            new ColorName("Smoky Topaz", 0x933D41),
            new ColorName("Snow", 0xFFFAFA),
            new ColorName("Soap", 0xCEC8EF),
            new ColorName("Soldier Green", 0x545A2C),
            new ColorName("Solid pink", 0x893843),
            new ColorName("Sonic silver", 0x757575),
            new ColorName("Spartan Crimson", 0x9E1316),
            new ColorName("Space cadet", 0x1D2951),
            new ColorName("Spanish bistre", 0x807532),
            new ColorName("Spanish blue", 0x0070B8),
            new ColorName("Spanish carmine", 0xD10047),
            new ColorName("Spanish crimson", 0xE51A4C),
            new ColorName("Spanish gray", 0x989898),
            new ColorName("Spanish green", 0x009150),
            new ColorName("Spanish orange", 0xE86100),
            new ColorName("Spanish pink", 0xF7BFBE),
            new ColorName("Spanish purple", 0x66033C),
            new ColorName("Spanish red", 0xE60026),
            new ColorName("Spanish sky blue", 0x00FFFF),
            new ColorName("Spanish violet", 0x4C2882),
            new ColorName("Spanish viridian", 0x007F5C),
            new ColorName("Spanish yellow", 0xF6B511),
            new ColorName("Spicy mix", 0x8B5f4D),
            new ColorName("Spiro Disco Ball", 0x0FC0FC),
            new ColorName("Spring bud", 0xA7FC00),
            new ColorName("Spring Frost", 0x87FF2A),
            new ColorName("Spring green", 0x00FF7F),
            new ColorName("Spring green (Crayola)", 0xECEBBD),
            new ColorName("Sprint Red", 0xEC2131),
            new ColorName("Sprint Yellow", 0xFFDD05),
            new ColorName("Star command blue", 0x007BB8),
            new ColorName("Steel blue", 0x4682B4),
            new ColorName("Steel pink", 0xCC33CC),
            new ColorName("Steel Teal", 0x5F8A8B),
            new ColorName("Stil de grain yellow", 0xFADA5E),
            new ColorName("Stizza", 0x990000),
            new ColorName("Stormcloud", 0x4F666A),
            new ColorName("Stone Terrace", 0xA09484),
            new ColorName("Straw", 0xE4D96F),
            new ColorName("Strawberry", 0xFC5A8D),
            new ColorName("Stop red", 0xCF142B),
            new ColorName("Strawberry iced tea", 0xFC5A8D),
            new ColorName("Strawberry red", 0xC83F49),
            new ColorName("Sugar Plum", 0x914E75),
            new ColorName("Sunburnt Cyclops", 0xFF404C),
            new ColorName("Sunglow", 0xFFCC33),
            new ColorName("Sunny", 0xF2F27A),
            new ColorName("Sunray", 0xE3AB57),
            new ColorName("Sunset", 0xFAD6A5),
            new ColorName("Sunset Yellow", 0xFFC922),
            new ColorName("Super pink", 0xCF6BA9),
            new ColorName("Sweet Brown", 0xA83731),
            new ColorName("Sweet Sixteen", 0xF29EAB),
            new ColorName("Tan", 0xD2B48C),
            new ColorName("Tan (Crayola)", 0xD99A6C),
            new ColorName("Tangelo", 0xF94D00),
            new ColorName("Tangerine", 0xF28500),
            new ColorName("Tangerine yellow", 0xFFCC00),
            new ColorName("Tango pink", 0xE4717A),
            new ColorName("Taobao Orange", 0xFF4200),
            new ColorName("Tart Orange", 0xFB4D46),
            new ColorName("Taupe", 0x483C32),
            new ColorName("Taupe gray", 0x8B8589),
            new ColorName("Tea green", 0xD0F0C0),
            new ColorName("Tea rose", 0xF88379),
            new ColorName("Tea rose", 0xF4C2C2),
            new ColorName("Teal", 0x008080),
            new ColorName("Teal blue", 0x367588),
            new ColorName("Teal deer", 0x99E6B3),
            new ColorName("Teal green", 0x00827F),
            new ColorName("Telemagenta", 0xCF3476),
            new ColorName("Temptress", 0x3C2126),
            new ColorName("Tenné (tawny)", 0xCD5700),
            new ColorName("Terra cotta", 0xE2725B),
            new ColorName("Thistle", 0xD8BFD8),
            new ColorName("Thistle (Crayola)", 0xEBB0D7),
            new ColorName("Thulian pink", 0xDE6FA1),
            new ColorName("Tickle Me Pink", 0xFC89AC),
            new ColorName("Tiffany Blue", 0x0ABAB5),
            new ColorName("Tiger's eye", 0xE08D3C),
            new ColorName("Timberwolf", 0xDBD7D2),
            new ColorName("Titanium", 0x878681),
            new ColorName("Titanium yellow", 0xEEE600),
            new ColorName("Tomato", 0xFF6347),
            new ColorName("Tomato sauce", 0xB21807),
            new ColorName("Toolbox", 0x746CC0),
            new ColorName("Tooth", 0xFFFAFA),
            new ColorName("Topaz", 0xFFC87C),
            new ColorName("Tractor red", 0xFD0E35),
            new ColorName("Trolley grey", 0x808080),
            new ColorName("Tropical rain forest", 0x00755E),
            new ColorName("Tropical violet", 0xCDA4DE),
            new ColorName("True Blue", 0x2D68C4),
            new ColorName("Tufts blue", 0x3E8EDE),
            new ColorName("Tulip", 0xFF878D),
            new ColorName("Tumbleweed", 0xDEAA88),
            new ColorName("Turkish rose", 0xB57281),
            new ColorName("Turquoise", 0x40E0D0),
            new ColorName("Turquoise blue", 0x00FFEF),
            new ColorName("Turquoise green", 0xA0D6B4),
            new ColorName("Turquoise Surf", 0x00C5CD),
            new ColorName("Turtle green", 0x8A9A5B),
            new ColorName("Tuscan", 0xFAD6A5),
            new ColorName("Tuscan brown", 0x6F4E37),
            new ColorName("Tuscan red", 0x7C4848),
            new ColorName("Tuscan tan", 0xA67B5B),
            new ColorName("Tuscany", 0xC09999),
            new ColorName("Twilight lavender", 0x8A496B),
            new ColorName("Twitter blue", 0x26A7DE),
            new ColorName("Tyrian purple", 0x66023C),
            new ColorName("UA blue", 0x0033AA),
            new ColorName("UA red", 0xD9004C),
            new ColorName("Ube", 0x8878C3),
            new ColorName("UCLA blue", 0x536895),
            new ColorName("UCLA gold", 0xFFB300),
            new ColorName("UE red", 0xBA0001),
            new ColorName("UFO Green", 0x3CD070),
            new ColorName("Ultramarine", 0x3F00FF),
            new ColorName("Ultramarine blue", 0x4166F5),
            new ColorName("Ultra pink", 0xFF6FFF),
            new ColorName("Ultra red", 0xFC6C85),
            new ColorName("Umber", 0x635147),
            new ColorName("Unbleached silk", 0xFFDDCA),
            new ColorName("United Nations blue", 0x5B92E5),
            new ColorName("University of Alabama Crimson", 0x9E1B32),
            new ColorName("University of California Gold", 0xB78727),
            new ColorName("University of Georgia Red", 0xBA0C2F),
            new ColorName("University of Kentucky Blue", 0x0033A0),
            new ColorName("University of Louisville Red", 0xAD0000),
            new ColorName("University of Pikeville Orange", 0xEA6E1E),
            new ColorName("University of Tennessee Orange", 0xF77F00),
            new ColorName("Unmellow yellow", 0xFFFF66),
            new ColorName("UP Forest green", 0x014421),
            new ColorName("UP maroon", 0x7B1113),
            new ColorName("Upsdell red", 0xAE2029),
            new ColorName("Urobilin", 0xE1AD21),
            new ColorName("USAFA blue", 0x004F98),
            new ColorName("USC Cardinal", 0x990000),
            new ColorName("USC Gold", 0xFFCC00),
            new ColorName("Utah Crimson", 0xD3003F),
            new ColorName("Vampire black", 0x080808),
            new ColorName("Van Dyke brown", 0x664228),
            new ColorName("Vanilla", 0xF3E5AB),
            new ColorName("Vanilla ice", 0xF38FA9),
            new ColorName("Vegas gold", 0xC5B358),
            new ColorName("Venetian red", 0xC80815),
            new ColorName("Verdigris", 0x43B3AE),
            new ColorName("Verizon Red", 0xCD040B),
            new ColorName("Verizon Red (2000-2015)", 0xEC1C24),
            new ColorName("Vermilion", 0xE34234),
            new ColorName("Vermilion", 0xD9381E),
            new ColorName("Veronica", 0xA020F0),
            new ColorName("Verse green", 0x18880d),
            new ColorName("Very light azure", 0x74BBFB),
            new ColorName("Very light blue", 0x6666FF),
            new ColorName("Very light malachite green", 0x64E986),
            new ColorName("Very light tangelo", 0xFFB077),
            new ColorName("Very pale orange", 0xFFDFBF),
            new ColorName("Very pale yellow", 0xFFFFBF),
            new ColorName("Vine Green", 0x38A32A),
            new ColorName("Violet", 0x8F00FF),
            new ColorName("Violet (color wheel)", 0x7F00FF),
            new ColorName("Violet (crayola)", 0x963D7F),
            new ColorName("Violet (RYB)", 0x8601AF),
            new ColorName("Violet (web)", 0xEE82EE),
            new ColorName("Violet-blue", 0x324AB2),
            new ColorName("Violet-blue (Crayola)", 0x766EC8),
            new ColorName("Violet-red", 0xF75394),
            new ColorName("Violet-red", 0x891446),
            new ColorName("Violets Are Blue", 0x8366F4),
            new ColorName("Violin Brown", 0x674403),
            new ColorName("Viridian", 0x40826D),
            new ColorName("Viridian green", 0x009698),
            new ColorName("Vista blue", 0x7C9ED9),
            new ColorName("Vivaldi Red", 0xEF3939),
            new ColorName("Vivid amber", 0xCC9900),
            new ColorName("Vivid auburn", 0x922724),
            new ColorName("Vivid burgundy", 0x9F1D35),
            new ColorName("Vivid cerise", 0xDA1D81),
            new ColorName("Vivid cerulean", 0x00AAEE),
            new ColorName("Vivid crimson", 0xCC0033),
            new ColorName("Vivid gamboge", 0xFF9900),
            new ColorName("Vivid lime green", 0xA6D608),
            new ColorName("Vivid malachite", 0x00CC33),
            new ColorName("Vivid mulberry", 0xB80CE3),
            new ColorName("Vivid orange", 0xFF5F00),
            new ColorName("Vivid orange peel", 0xFFA000),
            new ColorName("Vivid orchid", 0xCC00FF),
            new ColorName("Vivid raspberry", 0xFF006C),
            new ColorName("Vivid red", 0xF70D1A),
            new ColorName("Vivid red-tangelo", 0xDF6124),
            new ColorName("Vivid sky blue", 0x00CCFF),
            new ColorName("Vivid tangelo", 0xF07427),
            new ColorName("Vivid tangerine", 0xFFA089),
            new ColorName("Vivid vermilion", 0xE56024),
            new ColorName("Vivid violet", 0x9F00FF),
            new ColorName("Vivid yellow", 0xFFE302),
            new ColorName("Vodka", 0xBFC0EE),
            new ColorName("Volt", 0xCEFF00),
            new ColorName("Wageningen green", 0x34B233),
            new ColorName("Walmart blue", 0x007DC6),
            new ColorName("Walmart blue (Truck)", 0x00317E),
            new ColorName("Walmart blue (Website)", 0x0879C9),
            new ColorName("Walmart blue (1992–2008)", 0x2F39A8),
            new ColorName("Walmart blue (1981–1992)", 0x1D2CA0),
            new ColorName("Walmart blue (1964–1981)", 0x030303),
            new ColorName("Walmart blue (1962–1964)", 0x0C5DA7),
            new ColorName("Walmart Market Green", 0xA8F300),
            new ColorName("Walmart Neighborhood Market Green", 0x88C021),
            new ColorName("Walmart Neighborhood Market Green (2010-2011)", 0x55C500),
            new ColorName("Walmart Neighborhood Market Green (2008-2010)", 0x327A28),
            new ColorName("Walmart Neighborhood Market Green (1998-2008)", 0x106B4A),
            new ColorName("Warm black", 0x004242),
            new ColorName("Water", 0xD4F1F9),
            new ColorName("Watermelon", 0xF05C85),
            new ColorName("Watermelon red", 0xBF4147),
            new ColorName("Watermelon Yellow", 0xEEFF1B),
            new ColorName("Waterspout", 0xA4F4F9),
            new ColorName("Weebly Blue", 0x1F8EED),
            new ColorName("Weebly Orange", 0xFF9A00),
            new ColorName("Weldon Blue", 0x7C98AB),
            new ColorName("Wendy's Red", 0xDD1438),
            new ColorName("Wendy's Red (2007-2013)", 0xCD022D),
            new ColorName("Wendy's Red (1975-2007)", 0xED1B24),
            new ColorName("Wendy's Red (1971-1975)", 0xEE3A43),
            new ColorName("Wendy's Red (1969-1971)", 0xEE3942),
            new ColorName("Wenge", 0x645452),
            new ColorName("Wheat", 0xF5DEB3),
            new ColorName("White", 0xFFFFFF),
            new ColorName("White chocolate", 0xEDE6D6),
            new ColorName("White coffee", 0xE6E0D4),
            new ColorName("White smoke", 0xF5F5F5),
            new ColorName("Wild blue yonder", 0xA2ADD0),
            new ColorName("Wild orchid", 0xD470A2),
            new ColorName("Wild Strawberry", 0xFF43A4),
            new ColorName("Wild watermelon", 0xFC6C85),
            new ColorName("Willpower orange", 0xFD5800),
            new ColorName("Windsor tan", 0xA75502),
            new ColorName("Wine", 0x722F37),
            new ColorName("Wine red", 0xB11226),
            new ColorName("Wine dregs", 0x673147),
            new ColorName("Winter Sky", 0xFF007C),
            new ColorName("Winter Wizard", 0xA0E6FF),
            new ColorName("Wintergreen Dream", 0x56887D),
            new ColorName("Wisteria", 0xC9A0DC),
            new ColorName("Wood brown", 0xC19A6B),
            new ColorName("Xanadu", 0x738678),
            new ColorName("Xbox Green", 0x0E7A0D),
            new ColorName("Xiaomi Orange", 0xFD4900),
            new ColorName("Yahoo Japan Red", 0xFF0033),
            new ColorName("Yahoo Purple", 0x4102B0),
            new ColorName("Yahoo Purple (1995)", 0x7C019A),
            new ColorName("Yale Blue", 0x0F4D92),
            new ColorName("Yankees blue", 0x1C2841),
            new ColorName("Yellow", 0xFFFF00),
            new ColorName("Yellow (Crayola)", 0xFCE883),
            new ColorName("Yellow (Munsell)", 0xEFCC00),
            new ColorName("Yellow (NCS)", 0xFFD300),
            new ColorName("Yellow (Pantone)", 0xFEDF00),
            new ColorName("Yellow (process)", 0xFFEF00),
            new ColorName("Yellow (RYB)", 0xFEFE33),
            new ColorName("Yellow-green", 0x9ACD32),
            new ColorName("Yellow-green (Crayola)", 0xC5E384),
            new ColorName("Yellow-green (Color Wheel)", 0x30B21A),
            new ColorName("Yellow Orange", 0xFFAE42),
            new ColorName("Yellow Orange (Color Wheel)", 0xFF9505),
            new ColorName("Yellow rose", 0xFFF000),
            new ColorName("Yellow Sunshine", 0xFFF700),
            new ColorName("YInMn Blue", 0x2E5090),
            new ColorName("Youtube red", 0xB2071D),
            new ColorName("Zaffre", 0x0014A8),
            new ColorName("Zebra White", 0xF5F5F5),
            new ColorName("Zinnwaldite brown", 0x2C1608),
            new ColorName("Zomp", 0x39A78E),
            new ColorName("ZTE Blue", 0x4286D2),
            new ColorName("ZTE Blue (1985-2015)", 0x2056AE)
    };


}
